version: 0.2

phases:
  install:
    commands1:
      - echo Ensuring /var/www/html exists...
      - yum update -y
      - yum install nginx -y

  build:
    commands2:
      - echo HELLO SYED MOIZ
      - mkdir -p /var/www/html
      - cp index.html /var/www/html/

artifacts:
  files:
    - index.html
