version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y nginx

phases:
  build:
    commands:
      - echo "Build phase (no actions needed)"

artifacts:
  files:
    - '**/*'
