version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  pre_build:
    commands:
      - echo Preparing to build...
  build:
    commands:
      - echo Hello, World!
  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/*'
