version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y nginx

  build:
    commands:
      - echo "Listing files to check for index.html"
      - ls -la
      - echo "Copying index.html to /usr/share/nginx/html"
      - cp index.html /usr/share/nginx/html/index.html

artifacts:
  files:
    - '**/*'
