version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y nginx

  build:
    commands:
      - echo "Copying index.html to /var/www/html"
      - cp index.html /var/www/html/index.html

artifacts:
  files:
    - '**/*'
